---
jenkins_admin_password: "votre_mot_de_passe_securise"
jenkins_url: "http://jenkins.local:8080"
sonar_url: "http://127.0.0.1:9000"
jenkins_sonar_server_token: "sqa_0dff631452d1024f7ef9a24e03d013fcc5f7921e"
allowed_networks:
  - "192.168.1.0/24"
  # Ajoutez d'autres réseaux si nécessaire
