---
- name: install didier ros controller docker-arm64 image on pios
  hosts: glove-right
#  become: yes

  vars_files:
  - vars/main.yml

  roles:
    - role: dir_struct
      vars:
      - directories:
          - "{{ ros2_ws }}/build"
          - "{{ ros2_ws }}/install"
          - "{{ ros2_ws }}/log"
          - "{{ ros2_ws }}/python-lib"
          - "{{ ros2_ws }}/src/{{ project_ros_dir }}"
          - "scripts"
    - role: synchronise
      become: yes
    - role: linux-package
      vars:
      - package_file: "packages-rpi.txt"
    - role: download-install-deb-from-url
      vars:
        - debian_packages_urls:
            - "https://download.docker.com/linux/debian/dists/bookworm/pool/stable/arm64/containerd.io_1.6.28-2_arm64.deb"
            - "https://download.docker.com/linux/debian/dists/bookworm/pool/stable/arm64/docker-ce-cli_26.0.0-1~debian.12~bookworm_arm64.deb"
            - "https://download.docker.com/linux/debian/dists/bookworm/pool/stable/arm64/docker-ce_23.0.0-1~debian.12~bookworm_arm64.deb"
            - "https://download.docker.com/linux/debian/dists/bookworm/pool/stable/arm64/docker-buildx-plugin_0.13.1-1~debian.12~bookworm_arm64.deb"
            - "https://download.docker.com/linux/debian/dists/bookworm/pool/stable/arm64/docker-compose-plugin_2.25.0-1~debian.12~bookworm_arm64.deb"
    #- role: docker-arm64
    - role: set-bashrc
      vars:
        set_bashrc_project_file: "{{ local_projects_dir }}/{{ local_project_dir }}/conf/rpi/project_bash"
    - role: activate-spi
#    - role: screen-config
    #- role: desktop_lunch
    - role: start-scripts
    - role: services
      become: yes
    - role: command_root
      vars:
        command: "reboot"
#    - role: screen-config
