---
- name: "\e[1;31m install {{ target_group }} on pios full \e[0m"
  hosts: "{{ target_group }}"
#  become: yes

  vars_files:
  - vars/main.yml

  roles:
    #- role: info
    - role: dir_struct
      directories:
          - "{{ ros2_ws }}/build"
          - "{{ ros2_ws }}/install"
          - "{{ ros2_ws }}/log"
          - "{{ ros2_ws }}/src/{{ project_ros_dir }}"
          - "scripts"
    - role: synchronise
      become: yes
    - role: packages
      vars:
      - package_file: "packages-rpi.txt"
    - role: download-install-deb-from-url
      vars:
        - debian_packages_urls:
            - "https://download.docker.com/linux/debian/dists/bookworm/pool/stable/arm64/containerd.io_1.7.25-1_arm64.deb"
            - "https://download.docker.com/linux/debian/dists/bookworm/pool/stable/arm64/docker-ce-cli_28.0.0-1~debian.12~bookworm_arm64.deb"
            - "https://download.docker.com/linux/debian/dists/bookworm/pool/stable/arm64/docker-ce_28.0.0-1~debian.12~bookworm_arm64.deb"
            - "https://download.docker.com/linux/debian/dists/bookworm/pool/stable/arm64/docker-buildx-plugin_0.21.0-1~debian.12~bookworm_arm64.deb"
            - "https://download.docker.com/linux/debian/dists/bookworm/pool/stable/arm64/docker-compose-plugin_2.33.0-1~debian.12~bookworm_arm64.deb"
    #- role: docker-arm64
    - role: set-bashrc
    - role: start-scripts
    - role: desktop_lunch
    #- role: screen-config
    - role: command_root
      vars:
        command: "reboot"



#    - role: screen-config