---
sonar_docker_image: "sonarqube:community"
sonar_container_name: "sonarqube"
sonar_http_port: 9000
sonar_data_dir: "/var/lib/sonar/data"
sonar_extensions_dir: "/var/lib/sonar/extensions"
sonar_logs_dir: "/var/lib/sonar/logs"
sonar_directories_owner: "1000"
sonar_directories_group: "1000"
sonar_environment: {}
